server:
  port: 8080
spring:
  application:
    name: service-pichincha-desafio
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:desafiodb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  main:
    allow-bean-definition-overriding: true