	
INSERT INTO exchange_rate(MONEDA_ORIGEN,MONEDA_DESTINO, TIPO_CAMBIO) VALUES(0,1,3.90);
INSERT INTO exchange_rate(MONEDA_ORIGEN,MONEDA_DESTINO, TIPO_CAMBIO) VALUES(1,0,3.80);
INSERT INTO exchange_rate(MONEDA_ORIGEN,MONEDA_DESTINO, TIPO_CAMBIO) VALUES(0,2,4.60);  
INSERT INTO exchange_rate(MONEDA_ORIGEN,MONEDA_DESTINO, TIPO_CAMBIO) VALUES(2,0,4.50); 
INSERT INTO exchange_rate(MONEDA_ORIGEN,MONEDA_DESTINO, TIPO_CAMBIO) VALUES(1,2,3.60);  
INSERT INTO exchange_rate(MONEDA_ORIGEN,MONEDA_DESTINO, TIPO_CAMBIO) VALUES(2,1,3.50);   